---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: |
    Placeholder description...
  tags:
    - go
    - sherlock
    - kubernetes
    - dsp-devops
  annotations:
    github.com/project-slug: databiosphere/${{values.name}}
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner}}
  system: platform
  providesApis:
    - ${{values.name}}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.name}}-api
  description: |
    Placeholder API description...
  tags:
    - java
    - dsp
    - terra
    - ${{values.owner}}
  annotations:
    github.com/project-slug: broadinstitute/sherlock
spec:
  type: openapi
  lifecycle: experimental
  system: terra
  owner: ${{values.owner}}
  definition:
    $text: ./service/src/main/resources/api/openapi.yml
---
