name: ${{values.projecSlug}}

services:

  service:
    image: ${{values.name}}
    depends_on:
      - database
    environment:
      - DATABASE_HOSTNAME=database
    ports:
      - "8080:8080"

  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=dbuser    # default: postgres
#      - POSTGRES_DB=${{values.projectSlug}}_db
    ports:
      - "5432:5432"
    volumes:
      - ../build/tmp/postgres-data:/var/lib/postgresql/data
      - ./init-db/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
